### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by htz666** [naingyeminn/mm-kb#1]
hello,
can i use this on arch linux too? thank you.

**Comment by naingyeminn** [comment]
It was created to use only on Ubuntu. But it's just ibus-tables. Maybe you can use it as Arch supports IBus. https://wiki.archlinux.org/index.php/IBus
You can manually generate the db file as follow.
ibus-table-createdb -n mm-myanmar3.db -s ./src/tables/mm-myanmar3.txt
